//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDEX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp\\DDEX\\deezer")]
        public string NavigationFolderPath {
            get {
                return ((string)(this["NavigationFolderPath"]));
            }
            set {
                this["NavigationFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(P) 2016 LONGPLAY")]
        public string PLineText {
            get {
                return ((string)(this["PLineText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LONGPLAY")]
        public string LabelName {
            get {
                return ((string)(this["LabelName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Composer;Producer;Lyricist;Arranger")]
        public string IndirectContributors {
            get {
                return ((string)(this["IndirectContributors"]));
            }
            set {
                this["IndirectContributors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FeaturedArtist")]
        public string DisplayArtistRoles {
            get {
                return ((string)(this["DisplayArtistRoles"]));
            }
            set {
                this["DisplayArtistRoles"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PADPIDA20160517080")]
        public string DeezerSenderPartyID {
            get {
                return ((string)(this["DeezerSenderPartyID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PADPIDA2011021513H")]
        public string DeezerRecipientPartyID {
            get {
                return ((string)(this["DeezerRecipientPartyID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEEZER")]
        public string DeezerRecipientPartyName {
            get {
                return ((string)(this["DeezerRecipientPartyName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LONGPLAY")]
        public string DeezerSenderPartyName {
            get {
                return ((string)(this["DeezerSenderPartyName"]));
            }
            set {
                this["DeezerSenderPartyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PADPIDA20160517080")]
        public string PandoraSenderPartyID {
            get {
                return ((string)(this["PandoraSenderPartyID"]));
            }
            set {
                this["PandoraSenderPartyID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PADPIDA20140404055")]
        public string PandoraRecipientPartyID {
            get {
                return ((string)(this["PandoraRecipientPartyID"]));
            }
            set {
                this["PandoraRecipientPartyID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LONGPLAY")]
        public string PandoraSenderPartyName {
            get {
                return ((string)(this["PandoraSenderPartyName"]));
            }
            set {
                this["PandoraSenderPartyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PANDORA")]
        public string PandoraRecipientPartyName {
            get {
                return ((string)(this["PandoraRecipientPartyName"]));
            }
            set {
                this["PandoraRecipientPartyName"] = value;
            }
        }
    }
}
